// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ortools/linear_solver/linear_solver.proto

package com.google.ortools.linearsolver;

/**
 * <pre>
 * Indicator constraints encode the activation or deactivation of linear
 * constraints given the value of one Boolean variable in the model. For
 * example:
 *     y = 0 =&gt; 2 * x1 + 3 * x2 &gt;= 42
 * The 2 * x1 + 3 * x2 &gt;= 42 constraint is only active if the variable y is
 * equal to 0.
 * As of 2019/04, only SCIP, CP-SAT and Gurobi support this constraint type.
 * </pre>
 *
 * Protobuf type {@code operations_research.MPIndicatorConstraint}
 */
public final class MPIndicatorConstraint extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:operations_research.MPIndicatorConstraint)
    MPIndicatorConstraintOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MPIndicatorConstraint.newBuilder() to construct.
  private MPIndicatorConstraint(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MPIndicatorConstraint() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MPIndicatorConstraint();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MPIndicatorConstraint(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            bitField0_ |= 0x00000001;
            varIndex_ = input.readInt32();
            break;
          }
          case 16: {
            bitField0_ |= 0x00000002;
            varValue_ = input.readInt32();
            break;
          }
          case 26: {
            com.google.ortools.linearsolver.MPConstraintProto.Builder subBuilder = null;
            if (((bitField0_ & 0x00000004) != 0)) {
              subBuilder = constraint_.toBuilder();
            }
            constraint_ = input.readMessage(com.google.ortools.linearsolver.MPConstraintProto.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(constraint_);
              constraint_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000004;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.ortools.linearsolver.LinearSolver.internal_static_operations_research_MPIndicatorConstraint_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.ortools.linearsolver.LinearSolver.internal_static_operations_research_MPIndicatorConstraint_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.ortools.linearsolver.MPIndicatorConstraint.class, com.google.ortools.linearsolver.MPIndicatorConstraint.Builder.class);
  }

  private int bitField0_;
  public static final int VAR_INDEX_FIELD_NUMBER = 1;
  private int varIndex_;
  /**
   * <pre>
   * Variable index (w.r.t. the "variable" field of MPModelProto) of the Boolean
   * variable used as indicator.
   * </pre>
   *
   * <code>optional int32 var_index = 1;</code>
   * @return Whether the varIndex field is set.
   */
  @java.lang.Override
  public boolean hasVarIndex() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Variable index (w.r.t. the "variable" field of MPModelProto) of the Boolean
   * variable used as indicator.
   * </pre>
   *
   * <code>optional int32 var_index = 1;</code>
   * @return The varIndex.
   */
  @java.lang.Override
  public int getVarIndex() {
    return varIndex_;
  }

  public static final int VAR_VALUE_FIELD_NUMBER = 2;
  private int varValue_;
  /**
   * <pre>
   * Value the above variable should take. Must be 0 or 1.
   * </pre>
   *
   * <code>optional int32 var_value = 2;</code>
   * @return Whether the varValue field is set.
   */
  @java.lang.Override
  public boolean hasVarValue() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * Value the above variable should take. Must be 0 or 1.
   * </pre>
   *
   * <code>optional int32 var_value = 2;</code>
   * @return The varValue.
   */
  @java.lang.Override
  public int getVarValue() {
    return varValue_;
  }

  public static final int CONSTRAINT_FIELD_NUMBER = 3;
  private com.google.ortools.linearsolver.MPConstraintProto constraint_;
  /**
   * <pre>
   * The constraint activated by the indicator variable.
   * </pre>
   *
   * <code>optional .operations_research.MPConstraintProto constraint = 3;</code>
   * @return Whether the constraint field is set.
   */
  @java.lang.Override
  public boolean hasConstraint() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <pre>
   * The constraint activated by the indicator variable.
   * </pre>
   *
   * <code>optional .operations_research.MPConstraintProto constraint = 3;</code>
   * @return The constraint.
   */
  @java.lang.Override
  public com.google.ortools.linearsolver.MPConstraintProto getConstraint() {
    return constraint_ == null ? com.google.ortools.linearsolver.MPConstraintProto.getDefaultInstance() : constraint_;
  }
  /**
   * <pre>
   * The constraint activated by the indicator variable.
   * </pre>
   *
   * <code>optional .operations_research.MPConstraintProto constraint = 3;</code>
   */
  @java.lang.Override
  public com.google.ortools.linearsolver.MPConstraintProtoOrBuilder getConstraintOrBuilder() {
    return constraint_ == null ? com.google.ortools.linearsolver.MPConstraintProto.getDefaultInstance() : constraint_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeInt32(1, varIndex_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeInt32(2, varValue_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(3, getConstraint());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, varIndex_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, varValue_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getConstraint());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.ortools.linearsolver.MPIndicatorConstraint)) {
      return super.equals(obj);
    }
    com.google.ortools.linearsolver.MPIndicatorConstraint other = (com.google.ortools.linearsolver.MPIndicatorConstraint) obj;

    if (hasVarIndex() != other.hasVarIndex()) return false;
    if (hasVarIndex()) {
      if (getVarIndex()
          != other.getVarIndex()) return false;
    }
    if (hasVarValue() != other.hasVarValue()) return false;
    if (hasVarValue()) {
      if (getVarValue()
          != other.getVarValue()) return false;
    }
    if (hasConstraint() != other.hasConstraint()) return false;
    if (hasConstraint()) {
      if (!getConstraint()
          .equals(other.getConstraint())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasVarIndex()) {
      hash = (37 * hash) + VAR_INDEX_FIELD_NUMBER;
      hash = (53 * hash) + getVarIndex();
    }
    if (hasVarValue()) {
      hash = (37 * hash) + VAR_VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getVarValue();
    }
    if (hasConstraint()) {
      hash = (37 * hash) + CONSTRAINT_FIELD_NUMBER;
      hash = (53 * hash) + getConstraint().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.ortools.linearsolver.MPIndicatorConstraint parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.ortools.linearsolver.MPIndicatorConstraint parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.ortools.linearsolver.MPIndicatorConstraint parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.ortools.linearsolver.MPIndicatorConstraint parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.ortools.linearsolver.MPIndicatorConstraint parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.ortools.linearsolver.MPIndicatorConstraint parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.ortools.linearsolver.MPIndicatorConstraint parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.ortools.linearsolver.MPIndicatorConstraint parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.ortools.linearsolver.MPIndicatorConstraint parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.google.ortools.linearsolver.MPIndicatorConstraint parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.ortools.linearsolver.MPIndicatorConstraint parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.ortools.linearsolver.MPIndicatorConstraint parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.ortools.linearsolver.MPIndicatorConstraint prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Indicator constraints encode the activation or deactivation of linear
   * constraints given the value of one Boolean variable in the model. For
   * example:
   *     y = 0 =&gt; 2 * x1 + 3 * x2 &gt;= 42
   * The 2 * x1 + 3 * x2 &gt;= 42 constraint is only active if the variable y is
   * equal to 0.
   * As of 2019/04, only SCIP, CP-SAT and Gurobi support this constraint type.
   * </pre>
   *
   * Protobuf type {@code operations_research.MPIndicatorConstraint}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:operations_research.MPIndicatorConstraint)
      com.google.ortools.linearsolver.MPIndicatorConstraintOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.ortools.linearsolver.LinearSolver.internal_static_operations_research_MPIndicatorConstraint_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.ortools.linearsolver.LinearSolver.internal_static_operations_research_MPIndicatorConstraint_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.ortools.linearsolver.MPIndicatorConstraint.class, com.google.ortools.linearsolver.MPIndicatorConstraint.Builder.class);
    }

    // Construct using com.google.ortools.linearsolver.MPIndicatorConstraint.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getConstraintFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      varIndex_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      varValue_ = 0;
      bitField0_ = (bitField0_ & ~0x00000002);
      if (constraintBuilder_ == null) {
        constraint_ = null;
      } else {
        constraintBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.ortools.linearsolver.LinearSolver.internal_static_operations_research_MPIndicatorConstraint_descriptor;
    }

    @java.lang.Override
    public com.google.ortools.linearsolver.MPIndicatorConstraint getDefaultInstanceForType() {
      return com.google.ortools.linearsolver.MPIndicatorConstraint.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.ortools.linearsolver.MPIndicatorConstraint build() {
      com.google.ortools.linearsolver.MPIndicatorConstraint result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.ortools.linearsolver.MPIndicatorConstraint buildPartial() {
      com.google.ortools.linearsolver.MPIndicatorConstraint result = new com.google.ortools.linearsolver.MPIndicatorConstraint(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.varIndex_ = varIndex_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.varValue_ = varValue_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        if (constraintBuilder_ == null) {
          result.constraint_ = constraint_;
        } else {
          result.constraint_ = constraintBuilder_.build();
        }
        to_bitField0_ |= 0x00000004;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.ortools.linearsolver.MPIndicatorConstraint) {
        return mergeFrom((com.google.ortools.linearsolver.MPIndicatorConstraint)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.ortools.linearsolver.MPIndicatorConstraint other) {
      if (other == com.google.ortools.linearsolver.MPIndicatorConstraint.getDefaultInstance()) return this;
      if (other.hasVarIndex()) {
        setVarIndex(other.getVarIndex());
      }
      if (other.hasVarValue()) {
        setVarValue(other.getVarValue());
      }
      if (other.hasConstraint()) {
        mergeConstraint(other.getConstraint());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.ortools.linearsolver.MPIndicatorConstraint parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.google.ortools.linearsolver.MPIndicatorConstraint) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int varIndex_ ;
    /**
     * <pre>
     * Variable index (w.r.t. the "variable" field of MPModelProto) of the Boolean
     * variable used as indicator.
     * </pre>
     *
     * <code>optional int32 var_index = 1;</code>
     * @return Whether the varIndex field is set.
     */
    @java.lang.Override
    public boolean hasVarIndex() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Variable index (w.r.t. the "variable" field of MPModelProto) of the Boolean
     * variable used as indicator.
     * </pre>
     *
     * <code>optional int32 var_index = 1;</code>
     * @return The varIndex.
     */
    @java.lang.Override
    public int getVarIndex() {
      return varIndex_;
    }
    /**
     * <pre>
     * Variable index (w.r.t. the "variable" field of MPModelProto) of the Boolean
     * variable used as indicator.
     * </pre>
     *
     * <code>optional int32 var_index = 1;</code>
     * @param value The varIndex to set.
     * @return This builder for chaining.
     */
    public Builder setVarIndex(int value) {
      bitField0_ |= 0x00000001;
      varIndex_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Variable index (w.r.t. the "variable" field of MPModelProto) of the Boolean
     * variable used as indicator.
     * </pre>
     *
     * <code>optional int32 var_index = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearVarIndex() {
      bitField0_ = (bitField0_ & ~0x00000001);
      varIndex_ = 0;
      onChanged();
      return this;
    }

    private int varValue_ ;
    /**
     * <pre>
     * Value the above variable should take. Must be 0 or 1.
     * </pre>
     *
     * <code>optional int32 var_value = 2;</code>
     * @return Whether the varValue field is set.
     */
    @java.lang.Override
    public boolean hasVarValue() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Value the above variable should take. Must be 0 or 1.
     * </pre>
     *
     * <code>optional int32 var_value = 2;</code>
     * @return The varValue.
     */
    @java.lang.Override
    public int getVarValue() {
      return varValue_;
    }
    /**
     * <pre>
     * Value the above variable should take. Must be 0 or 1.
     * </pre>
     *
     * <code>optional int32 var_value = 2;</code>
     * @param value The varValue to set.
     * @return This builder for chaining.
     */
    public Builder setVarValue(int value) {
      bitField0_ |= 0x00000002;
      varValue_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Value the above variable should take. Must be 0 or 1.
     * </pre>
     *
     * <code>optional int32 var_value = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearVarValue() {
      bitField0_ = (bitField0_ & ~0x00000002);
      varValue_ = 0;
      onChanged();
      return this;
    }

    private com.google.ortools.linearsolver.MPConstraintProto constraint_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.ortools.linearsolver.MPConstraintProto, com.google.ortools.linearsolver.MPConstraintProto.Builder, com.google.ortools.linearsolver.MPConstraintProtoOrBuilder> constraintBuilder_;
    /**
     * <pre>
     * The constraint activated by the indicator variable.
     * </pre>
     *
     * <code>optional .operations_research.MPConstraintProto constraint = 3;</code>
     * @return Whether the constraint field is set.
     */
    public boolean hasConstraint() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * The constraint activated by the indicator variable.
     * </pre>
     *
     * <code>optional .operations_research.MPConstraintProto constraint = 3;</code>
     * @return The constraint.
     */
    public com.google.ortools.linearsolver.MPConstraintProto getConstraint() {
      if (constraintBuilder_ == null) {
        return constraint_ == null ? com.google.ortools.linearsolver.MPConstraintProto.getDefaultInstance() : constraint_;
      } else {
        return constraintBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * The constraint activated by the indicator variable.
     * </pre>
     *
     * <code>optional .operations_research.MPConstraintProto constraint = 3;</code>
     */
    public Builder setConstraint(com.google.ortools.linearsolver.MPConstraintProto value) {
      if (constraintBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        constraint_ = value;
        onChanged();
      } else {
        constraintBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <pre>
     * The constraint activated by the indicator variable.
     * </pre>
     *
     * <code>optional .operations_research.MPConstraintProto constraint = 3;</code>
     */
    public Builder setConstraint(
        com.google.ortools.linearsolver.MPConstraintProto.Builder builderForValue) {
      if (constraintBuilder_ == null) {
        constraint_ = builderForValue.build();
        onChanged();
      } else {
        constraintBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <pre>
     * The constraint activated by the indicator variable.
     * </pre>
     *
     * <code>optional .operations_research.MPConstraintProto constraint = 3;</code>
     */
    public Builder mergeConstraint(com.google.ortools.linearsolver.MPConstraintProto value) {
      if (constraintBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
            constraint_ != null &&
            constraint_ != com.google.ortools.linearsolver.MPConstraintProto.getDefaultInstance()) {
          constraint_ =
            com.google.ortools.linearsolver.MPConstraintProto.newBuilder(constraint_).mergeFrom(value).buildPartial();
        } else {
          constraint_ = value;
        }
        onChanged();
      } else {
        constraintBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <pre>
     * The constraint activated by the indicator variable.
     * </pre>
     *
     * <code>optional .operations_research.MPConstraintProto constraint = 3;</code>
     */
    public Builder clearConstraint() {
      if (constraintBuilder_ == null) {
        constraint_ = null;
        onChanged();
      } else {
        constraintBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }
    /**
     * <pre>
     * The constraint activated by the indicator variable.
     * </pre>
     *
     * <code>optional .operations_research.MPConstraintProto constraint = 3;</code>
     */
    public com.google.ortools.linearsolver.MPConstraintProto.Builder getConstraintBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getConstraintFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The constraint activated by the indicator variable.
     * </pre>
     *
     * <code>optional .operations_research.MPConstraintProto constraint = 3;</code>
     */
    public com.google.ortools.linearsolver.MPConstraintProtoOrBuilder getConstraintOrBuilder() {
      if (constraintBuilder_ != null) {
        return constraintBuilder_.getMessageOrBuilder();
      } else {
        return constraint_ == null ?
            com.google.ortools.linearsolver.MPConstraintProto.getDefaultInstance() : constraint_;
      }
    }
    /**
     * <pre>
     * The constraint activated by the indicator variable.
     * </pre>
     *
     * <code>optional .operations_research.MPConstraintProto constraint = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.ortools.linearsolver.MPConstraintProto, com.google.ortools.linearsolver.MPConstraintProto.Builder, com.google.ortools.linearsolver.MPConstraintProtoOrBuilder> 
        getConstraintFieldBuilder() {
      if (constraintBuilder_ == null) {
        constraintBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.ortools.linearsolver.MPConstraintProto, com.google.ortools.linearsolver.MPConstraintProto.Builder, com.google.ortools.linearsolver.MPConstraintProtoOrBuilder>(
                getConstraint(),
                getParentForChildren(),
                isClean());
        constraint_ = null;
      }
      return constraintBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:operations_research.MPIndicatorConstraint)
  }

  // @@protoc_insertion_point(class_scope:operations_research.MPIndicatorConstraint)
  private static final com.google.ortools.linearsolver.MPIndicatorConstraint DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.ortools.linearsolver.MPIndicatorConstraint();
  }

  public static com.google.ortools.linearsolver.MPIndicatorConstraint getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<MPIndicatorConstraint>
      PARSER = new com.google.protobuf.AbstractParser<MPIndicatorConstraint>() {
    @java.lang.Override
    public MPIndicatorConstraint parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MPIndicatorConstraint(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MPIndicatorConstraint> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MPIndicatorConstraint> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.ortools.linearsolver.MPIndicatorConstraint getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

