// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ortools/linear_solver/linear_solver.proto

package com.google.ortools.linearsolver;

public interface OptionalDoubleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:operations_research.OptionalDouble)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional double value = 1;</code>
   * @return Whether the value field is set.
   */
  boolean hasValue();
  /**
   * <code>optional double value = 1;</code>
   * @return The value.
   */
  double getValue();
}
