// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ortools/linear_solver/linear_solver.proto

package com.google.ortools.linearsolver;

public interface PartialVariableAssignmentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:operations_research.PartialVariableAssignment)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int32 var_index = 1 [packed = true];</code>
   * @return A list containing the varIndex.
   */
  java.util.List<java.lang.Integer> getVarIndexList();
  /**
   * <code>repeated int32 var_index = 1 [packed = true];</code>
   * @return The count of varIndex.
   */
  int getVarIndexCount();
  /**
   * <code>repeated int32 var_index = 1 [packed = true];</code>
   * @param index The index of the element to return.
   * @return The varIndex at the given index.
   */
  int getVarIndex(int index);

  /**
   * <code>repeated double var_value = 2 [packed = true];</code>
   * @return A list containing the varValue.
   */
  java.util.List<java.lang.Double> getVarValueList();
  /**
   * <code>repeated double var_value = 2 [packed = true];</code>
   * @return The count of varValue.
   */
  int getVarValueCount();
  /**
   * <code>repeated double var_value = 2 [packed = true];</code>
   * @param index The index of the element to return.
   * @return The varValue at the given index.
   */
  double getVarValue(int index);
}
