/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.ortools.constraintsolver;

public class AssignmentElement {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected AssignmentElement(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AssignmentElement obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mainJNI.delete_AssignmentElement(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public AssignmentElement() {
    this(mainJNI.new_AssignmentElement(), true);
  }

  public void activate() {
    mainJNI.AssignmentElement_activate(swigCPtr, this);
  }

  public void deactivate() {
    mainJNI.AssignmentElement_deactivate(swigCPtr, this);
  }

  public boolean activated() {
    return mainJNI.AssignmentElement_activated(swigCPtr, this);
  }

}
