/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.ortools.constraintsolver;

public class ChangeValue extends IntVarLocalSearchOperator {
  private transient long swigCPtr;

  protected ChangeValue(long cPtr, boolean cMemoryOwn) {
    super(mainJNI.ChangeValue_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ChangeValue obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mainJNI.delete_ChangeValue(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    mainJNI.ChangeValue_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    mainJNI.ChangeValue_change_ownership(this, swigCPtr, true);
  }

  public ChangeValue(IntVar[] vars) {
    this(mainJNI.new_ChangeValue(vars), true);
    mainJNI.ChangeValue_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public long modifyValue(long index, long value) {
    return mainJNI.ChangeValue_modifyValue(swigCPtr, this, index, value);
  }

  protected boolean oneNeighbor() {
    return (getClass() == ChangeValue.class) ? mainJNI.ChangeValue_oneNeighbor(swigCPtr, this) : mainJNI.ChangeValue_oneNeighborSwigExplicitChangeValue(swigCPtr, this);
  }

}
