/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.ortools.constraintsolver;

public class RevPartialSequence {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RevPartialSequence(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RevPartialSequence obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mainJNI.delete_RevPartialSequence(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public RevPartialSequence(int[] items) {
    this(mainJNI.new_RevPartialSequence__SWIG_0(items), true);
  }

  public RevPartialSequence(int size) {
    this(mainJNI.new_RevPartialSequence__SWIG_1(size), true);
  }

  public int numFirstRanked() {
    return mainJNI.RevPartialSequence_numFirstRanked(swigCPtr, this);
  }

  public int numLastRanked() {
    return mainJNI.RevPartialSequence_numLastRanked(swigCPtr, this);
  }

  public int size() {
    return mainJNI.RevPartialSequence_size(swigCPtr, this);
  }

  public void rankFirst(Solver solver, int elt) {
    mainJNI.RevPartialSequence_rankFirst(swigCPtr, this, Solver.getCPtr(solver), solver, elt);
  }

  public void rankLast(Solver solver, int elt) {
    mainJNI.RevPartialSequence_rankLast(swigCPtr, this, Solver.getCPtr(solver), solver, elt);
  }

  public boolean isRanked(int elt) {
    return mainJNI.RevPartialSequence_isRanked(swigCPtr, this, elt);
  }

  public String toString() {
    return mainJNI.RevPartialSequence_toString(swigCPtr, this);
  }

}
