// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ortools/constraint_solver/routing_parameters.proto

package com.google.ortools.constraintsolver;

public final class RoutingParameters {
  private RoutingParameters() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_operations_research_RoutingSearchParameters_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_operations_research_RoutingSearchParameters_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_operations_research_RoutingSearchParameters_LocalSearchNeighborhoodOperators_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_operations_research_RoutingSearchParameters_LocalSearchNeighborhoodOperators_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_operations_research_RoutingModelParameters_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_operations_research_RoutingModelParameters_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n2ortools/constraint_solver/routing_para" +
      "meters.proto\022\023operations_research\032\036googl" +
      "e/protobuf/duration.proto\032-ortools/const" +
      "raint_solver/routing_enums.proto\0321ortool" +
      "s/constraint_solver/solver_parameters.pr" +
      "oto\032#ortools/util/optional_boolean.proto" +
      "\"\361\034\n\027RoutingSearchParameters\022Q\n\027first_so" +
      "lution_strategy\030\001 \001(\01620.operations_resea" +
      "rch.FirstSolutionStrategy.Value\022.\n&use_u" +
      "nfiltered_first_solution_strategy\030\002 \001(\010\022" +
      "\037\n\027savings_neighbors_ratio\030\016 \001(\001\022&\n\036savi" +
      "ngs_max_memory_usage_bytes\030\027 \001(\001\022 \n\030savi" +
      "ngs_add_reverse_arcs\030\017 \001(\010\022\037\n\027savings_ar" +
      "c_coefficient\030\022 \001(\001\022\037\n\027savings_parallel_" +
      "routes\030\023 \001(\010\022/\n\'cheapest_insertion_farth" +
      "est_seeds_ratio\030\020 \001(\001\0229\n1cheapest_insert" +
      "ion_first_solution_neighbors_ratio\030\025 \001(\001" +
      "\0226\n.cheapest_insertion_ls_operator_neigh" +
      "bors_ratio\030\037 \001(\001\022)\n!christofides_use_min" +
      "imum_matching\030\036 \001(\010\022m\n\026local_search_oper" +
      "ators\030\003 \001(\0132M.operations_research.Routin" +
      "gSearchParameters.LocalSearchNeighborhoo" +
      "dOperators\0225\n-relocate_expensive_chain_n" +
      "um_arcs_to_consider\030\024 \001(\005\022:\n2heuristic_e" +
      "xpensive_chain_lns_num_arcs_to_consider\030" +
      "  \001(\005\022W\n\032local_search_metaheuristic\030\004 \001(" +
      "\01623.operations_research.LocalSearchMetah" +
      "euristic.Value\022.\n&guided_local_search_la" +
      "mbda_coefficient\030\005 \001(\001\022\036\n\026use_depth_firs" +
      "t_search\030\006 \001(\010\0224\n\006use_cp\030\034 \001(\0162$.operati" +
      "ons_research.OptionalBoolean\0228\n\nuse_cp_s" +
      "at\030\033 \001(\0162$.operations_research.OptionalB" +
      "oolean\022c\n\034continuous_scheduling_solver\030!" +
      " \001(\0162=.operations_research.RoutingSearch" +
      "Parameters.SchedulingSolver\022f\n\037mixed_int" +
      "eger_scheduling_solver\030\" \001(\0162=.operation" +
      "s_research.RoutingSearchParameters.Sched" +
      "ulingSolver\022\031\n\021optimization_step\030\007 \001(\001\022&" +
      "\n\036number_of_solutions_to_collect\030\021 \001(\005\022\026" +
      "\n\016solution_limit\030\010 \001(\003\022-\n\ntime_limit\030\t \001" +
      "(\0132\031.google.protobuf.Duration\0221\n\016lns_tim" +
      "e_limit\030\n \001(\0132\031.google.protobuf.Duration" +
      "\022\034\n\024use_full_propagation\030\013 \001(\010\022\022\n\nlog_se" +
      "arch\030\r \001(\010\022\037\n\027log_cost_scaling_factor\030\026 " +
      "\001(\001\022\027\n\017log_cost_offset\030\035 \001(\001\032\260\020\n LocalSe" +
      "archNeighborhoodOperators\022:\n\014use_relocat" +
      "e\030\001 \001(\0162$.operations_research.OptionalBo" +
      "olean\022?\n\021use_relocate_pair\030\002 \001(\0162$.opera" +
      "tions_research.OptionalBoolean\022E\n\027use_li" +
      "ght_relocate_pair\030\030 \001(\0162$.operations_res" +
      "earch.OptionalBoolean\022D\n\026use_relocate_ne" +
      "ighbors\030\003 \001(\0162$.operations_research.Opti" +
      "onalBoolean\022B\n\024use_relocate_subtrip\030\031 \001(" +
      "\0162$.operations_research.OptionalBoolean\022" +
      ":\n\014use_exchange\030\004 \001(\0162$.operations_resea" +
      "rch.OptionalBoolean\022?\n\021use_exchange_pair" +
      "\030\026 \001(\0162$.operations_research.OptionalBoo" +
      "lean\022B\n\024use_exchange_subtrip\030\032 \001(\0162$.ope" +
      "rations_research.OptionalBoolean\0227\n\tuse_" +
      "cross\030\005 \001(\0162$.operations_research.Option" +
      "alBoolean\022@\n\022use_cross_exchange\030\006 \001(\0162$." +
      "operations_research.OptionalBoolean\022J\n\034u" +
      "se_relocate_expensive_chain\030\027 \001(\0162$.oper" +
      "ations_research.OptionalBoolean\0229\n\013use_t" +
      "wo_opt\030\007 \001(\0162$.operations_research.Optio" +
      "nalBoolean\0228\n\nuse_or_opt\030\010 \001(\0162$.operati" +
      "ons_research.OptionalBoolean\022?\n\021use_lin_" +
      "kernighan\030\t \001(\0162$.operations_research.Op" +
      "tionalBoolean\0229\n\013use_tsp_opt\030\n \001(\0162$.ope" +
      "rations_research.OptionalBoolean\022=\n\017use_" +
      "make_active\030\013 \001(\0162$.operations_research." +
      "OptionalBoolean\022J\n\034use_relocate_and_make" +
      "_active\030\025 \001(\0162$.operations_research.Opti" +
      "onalBoolean\022?\n\021use_make_inactive\030\014 \001(\0162$" +
      ".operations_research.OptionalBoolean\022E\n\027" +
      "use_make_chain_inactive\030\r \001(\0162$.operatio" +
      "ns_research.OptionalBoolean\022=\n\017use_swap_" +
      "active\030\016 \001(\0162$.operations_research.Optio" +
      "nalBoolean\022F\n\030use_extended_swap_active\030\017" +
      " \001(\0162$.operations_research.OptionalBoole" +
      "an\022G\n\031use_node_pair_swap_active\030\024 \001(\0162$." +
      "operations_research.OptionalBoolean\022:\n\014u" +
      "se_path_lns\030\020 \001(\0162$.operations_research." +
      "OptionalBoolean\022?\n\021use_full_path_lns\030\021 \001" +
      "(\0162$.operations_research.OptionalBoolean" +
      "\0229\n\013use_tsp_lns\030\022 \001(\0162$.operations_resea" +
      "rch.OptionalBoolean\022>\n\020use_inactive_lns\030" +
      "\023 \001(\0162$.operations_research.OptionalBool" +
      "ean\022T\n&use_global_cheapest_insertion_pat" +
      "h_lns\030\033 \001(\0162$.operations_research.Option" +
      "alBoolean\022S\n%use_local_cheapest_insertio" +
      "n_path_lns\030\034 \001(\0162$.operations_research.O" +
      "ptionalBoolean\022_\n1use_global_cheapest_in" +
      "sertion_expensive_chain_lns\030\035 \001(\0162$.oper" +
      "ations_research.OptionalBoolean\022^\n0use_l" +
      "ocal_cheapest_insertion_expensive_chain_" +
      "lns\030\036 \001(\0162$.operations_research.Optional" +
      "Boolean\"3\n\020SchedulingSolver\022\t\n\005UNSET\020\000\022\010" +
      "\n\004GLOP\020\001\022\n\n\006CP_SAT\020\002\"\250\001\n\026RoutingModelPar" +
      "ameters\022J\n\021solver_parameters\030\001 \001(\0132/.ope" +
      "rations_research.ConstraintSolverParamet" +
      "ers\022!\n\031reduce_vehicle_cost_model\030\002 \001(\010\022\037" +
      "\n\027max_callback_cache_size\030\003 \001(\005BI\n#com.g" +
      "oogle.ortools.constraintsolverP\001\252\002\037Googl" +
      "e.OrTools.ConstraintSolverb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DurationProto.getDescriptor(),
          com.google.ortools.constraintsolver.RoutingEnums.getDescriptor(),
          com.google.ortools.constraintsolver.SolverParameters.getDescriptor(),
          com.google.ortools.util.OptionalBooleanOuterClass.getDescriptor(),
        });
    internal_static_operations_research_RoutingSearchParameters_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_operations_research_RoutingSearchParameters_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_operations_research_RoutingSearchParameters_descriptor,
        new java.lang.String[] { "FirstSolutionStrategy", "UseUnfilteredFirstSolutionStrategy", "SavingsNeighborsRatio", "SavingsMaxMemoryUsageBytes", "SavingsAddReverseArcs", "SavingsArcCoefficient", "SavingsParallelRoutes", "CheapestInsertionFarthestSeedsRatio", "CheapestInsertionFirstSolutionNeighborsRatio", "CheapestInsertionLsOperatorNeighborsRatio", "ChristofidesUseMinimumMatching", "LocalSearchOperators", "RelocateExpensiveChainNumArcsToConsider", "HeuristicExpensiveChainLnsNumArcsToConsider", "LocalSearchMetaheuristic", "GuidedLocalSearchLambdaCoefficient", "UseDepthFirstSearch", "UseCp", "UseCpSat", "ContinuousSchedulingSolver", "MixedIntegerSchedulingSolver", "OptimizationStep", "NumberOfSolutionsToCollect", "SolutionLimit", "TimeLimit", "LnsTimeLimit", "UseFullPropagation", "LogSearch", "LogCostScalingFactor", "LogCostOffset", });
    internal_static_operations_research_RoutingSearchParameters_LocalSearchNeighborhoodOperators_descriptor =
      internal_static_operations_research_RoutingSearchParameters_descriptor.getNestedTypes().get(0);
    internal_static_operations_research_RoutingSearchParameters_LocalSearchNeighborhoodOperators_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_operations_research_RoutingSearchParameters_LocalSearchNeighborhoodOperators_descriptor,
        new java.lang.String[] { "UseRelocate", "UseRelocatePair", "UseLightRelocatePair", "UseRelocateNeighbors", "UseRelocateSubtrip", "UseExchange", "UseExchangePair", "UseExchangeSubtrip", "UseCross", "UseCrossExchange", "UseRelocateExpensiveChain", "UseTwoOpt", "UseOrOpt", "UseLinKernighan", "UseTspOpt", "UseMakeActive", "UseRelocateAndMakeActive", "UseMakeInactive", "UseMakeChainInactive", "UseSwapActive", "UseExtendedSwapActive", "UseNodePairSwapActive", "UsePathLns", "UseFullPathLns", "UseTspLns", "UseInactiveLns", "UseGlobalCheapestInsertionPathLns", "UseLocalCheapestInsertionPathLns", "UseGlobalCheapestInsertionExpensiveChainLns", "UseLocalCheapestInsertionExpensiveChainLns", });
    internal_static_operations_research_RoutingModelParameters_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_operations_research_RoutingModelParameters_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_operations_research_RoutingModelParameters_descriptor,
        new java.lang.String[] { "SolverParameters", "ReduceVehicleCostModel", "MaxCallbackCacheSize", });
    com.google.protobuf.DurationProto.getDescriptor();
    com.google.ortools.constraintsolver.RoutingEnums.getDescriptor();
    com.google.ortools.constraintsolver.SolverParameters.getDescriptor();
    com.google.ortools.util.OptionalBooleanOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
