/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.ortools.util;

public class mainJNI {
  public final static native long new_Domain__SWIG_0();
  public final static native long new_Domain__SWIG_1(long jarg1);
  public final static native long new_Domain__SWIG_2(long jarg1, long jarg2);
  public final static native long Domain_allValues();
  public final static native long Domain_fromValues(long[] jarg1);
  public final static native long Domain_fromIntervals(long[][] jarg1);
  public final static native long Domain_fromFlatIntervals(long[] jarg1);
  public final static native long[] Domain_flattenedIntervals(long jarg1, Domain jarg1_);
  public final static native boolean Domain_isEmpty(long jarg1, Domain jarg1_);
  public final static native long Domain_size(long jarg1, Domain jarg1_);
  public final static native long Domain_min(long jarg1, Domain jarg1_);
  public final static native long Domain_max(long jarg1, Domain jarg1_);
  public final static native boolean Domain_contains(long jarg1, Domain jarg1_, long jarg2);
  public final static native long Domain_complement(long jarg1, Domain jarg1_);
  public final static native long Domain_negation(long jarg1, Domain jarg1_);
  public final static native long Domain_intersectionWith(long jarg1, Domain jarg1_, long jarg2, Domain jarg2_);
  public final static native long Domain_unionWith(long jarg1, Domain jarg1_, long jarg2, Domain jarg2_);
  public final static native long Domain_additionWith(long jarg1, Domain jarg1_, long jarg2, Domain jarg2_);
  public final static native String Domain_toString(long jarg1, Domain jarg1_);
  public final static native void delete_Domain(long jarg1);
  public final static native long new_SortedDisjointIntervalList__SWIG_0();
  public final static native long new_SortedDisjointIntervalList__SWIG_1(long[] jarg1, long[] jarg2);
  public final static native long new_SortedDisjointIntervalList__SWIG_2(int[] jarg1, int[] jarg2);
  public final static native long SortedDisjointIntervalList_buildComplementOnInterval(long jarg1, SortedDisjointIntervalList jarg1_, long jarg2, long jarg3);
  public final static native long SortedDisjointIntervalList_insertInterval(long jarg1, SortedDisjointIntervalList jarg1_, long jarg2, long jarg3);
  public final static native void SortedDisjointIntervalList_insertIntervals__SWIG_0(long jarg1, SortedDisjointIntervalList jarg1_, long[] jarg2, long[] jarg3);
  public final static native void SortedDisjointIntervalList_insertIntervals__SWIG_1(long jarg1, SortedDisjointIntervalList jarg1_, int[] jarg2, int[] jarg3);
  public final static native int SortedDisjointIntervalList_numIntervals(long jarg1, SortedDisjointIntervalList jarg1_);
  public final static native String SortedDisjointIntervalList_toString(long jarg1, SortedDisjointIntervalList jarg1_);
  public final static native void delete_SortedDisjointIntervalList(long jarg1);
}
