// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ortools/sat/cp_model.proto

package com.google.ortools.sat;

public interface IntervalConstraintProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:operations_research.sat.IntervalConstraintProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 start = 1;</code>
   * @return The start.
   */
  int getStart();

  /**
   * <code>int32 end = 2;</code>
   * @return The end.
   */
  int getEnd();

  /**
   * <code>int32 size = 3;</code>
   * @return The size.
   */
  int getSize();
}
