// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ortools/sat/cp_model.proto

package com.google.ortools.sat;

public interface NoOverlapConstraintProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:operations_research.sat.NoOverlapConstraintProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int32 intervals = 1;</code>
   * @return A list containing the intervals.
   */
  java.util.List<java.lang.Integer> getIntervalsList();
  /**
   * <code>repeated int32 intervals = 1;</code>
   * @return The count of intervals.
   */
  int getIntervalsCount();
  /**
   * <code>repeated int32 intervals = 1;</code>
   * @param index The index of the element to return.
   * @return The intervals at the given index.
   */
  int getIntervals(int index);
}
